server.port=7007
server.servlet.context-path=
server.max-http-request-header-size=50MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=100MB

# JWT
jwt.secret=changeme-backend-secret

# Local Database (DATABASE-per-tenant pattern - default local DB = dbgym)
# TSM me yaha comment hai, actual DB MysqlDataSourceService.loadDatabaseCredentialsFromLocalHost() se uthega
#microservice.local.database.name=dbgym
#microservice.local.database.port=3306
#microservice.local.database.username=root
#microservice.local.database.password=hrhk

# JPA / Hibernate (multitenancy managed programmatically in MultiTenancyJpaConfiguration)
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
